export const regions = [
    {
      "name": "Cape Town",
      "geography": "Africa",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "af-south-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Hong Kong",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-east-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Tokyo",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-northeast-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Seoul",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-northeast-2",
      "availabilityZoneCount": 4,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Osaka",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-northeast-3",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Mumbai",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-south-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Hyderabad",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-south-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Singapore",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-southeast-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Sydney",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-southeast-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Jakarta",
      "geography": "Asia Pacific",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ap-southeast-3",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Central",
      "geography": "Canada",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "ca-central-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Frankfurt",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-central-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Zurich",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-central-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Stockholm",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-north-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Milan",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-south-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Spain",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-south-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Ireland",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-west-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "London",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-west-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Paris",
      "geography": "Europe",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "eu-west-3",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "UAE",
      "geography": "Middle East",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "me-central-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Bahrain",
      "geography": "Middle East",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "me-south-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Sao Paulo",
      "geography": "South America",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "sa-east-1",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "N. Virginia",
      "geography": "US East",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "us-east-1",
      "availabilityZoneCount": 6,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Ohio",
      "geography": "US East",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "us-east-2",
      "availabilityZoneCount": 3,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "N. California",
      "geography": "US West",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "us-west-1",
      "availabilityZoneCount": 2,
      "restricted": false,
      "accessEnabled": true
    },
    {
      "name": "Oregon",
      "geography": "US West",
      "latitude": null,
      "longitude": null,
      "pairedRegion": null,
      "physicalLocation": null,
      "regionalname": null,
      "regionName": "us-west-2",
      "availabilityZoneCount": 4,
      "restricted": false,
      "accessEnabled": true
    }
  ]