export const regions = [
  {
    name: "Cape Town",
    geography: "Africa",
    regionName: "af-south-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Hong Kong",
    geography: "Asia Pacific",
    regionName: "ap-east-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Tokyo",
    geography: "Asia Pacific",
    regionName: "ap-northeast-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Seoul",
    geography: "Asia Pacific",
    regionName: "ap-northeast-2",
    availabilityZoneCount: 4,
  },
  {
    name: "Osaka",
    geography: "Asia Pacific",
    regionName: "ap-northeast-3",
    availabilityZoneCount: 3,
  },
  {
    name: "Mumbai",
    geography: "Asia Pacific",
    regionName: "ap-south-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Hyderabad",
    geography: "Asia Pacific",
    regionName: "ap-south-2",
    availabilityZoneCount: 3,
  },
  {
    name: "Singapore",
    geography: "Asia Pacific",
    regionName: "ap-southeast-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Sydney",
    geography: "Asia Pacific",
    regionName: "ap-southeast-2",
    availabilityZoneCount: 3,
  },
  {
    name: "Jakarta",
    geography: "Asia Pacific",
    regionName: "ap-southeast-3",
    availabilityZoneCount: 3,
  },
  {
    name: "Central",
    geography: "Canada",
    regionName: "ca-central-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Frankfurt",
    geography: "Europe",
    regionName: "eu-central-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Zurich",
    geography: "Europe",
    regionName: "eu-central-2",
    availabilityZoneCount: 3,
  },
  {
    name: "Stockholm",
    geography: "Europe",
    regionName: "eu-north-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Milan",
    geography: "Europe",
    regionName: "eu-south-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Spain",
    geography: "Europe",
    regionName: "eu-south-2",
    availabilityZoneCount: 3,
  },
  {
    name: "Ireland",
    geography: "Europe",
    regionName: "eu-west-1",
    availabilityZoneCount: 3,
  },
  {
    name: "London",
    geography: "Europe",
    regionName: "eu-west-2",
    availabilityZoneCount: 3,
  },
  {
    name: "Paris",
    geography: "Europe",
    regionName: "eu-west-3",
    availabilityZoneCount: 3,
  },
  {
    name: "UAE",
    geography: "Middle East",
    regionName: "me-central-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Bahrain",
    geography: "Middle East",
    regionName: "me-south-1",
    availabilityZoneCount: 3,
  },
  {
    name: "Sao Paulo",
    geography: "South America",
    regionName: "sa-east-1",
    availabilityZoneCount: 3,
  },
  {
    name: "N. Virginia",
    geography: "US East",
    regionName: "us-east-1",
    availabilityZoneCount: 6,
  },
  {
    name: "Ohio",
    geography: "US East",
    regionName: "us-east-2",
    availabilityZoneCount: 3,
  },
  {
    name: "N. California",
    geography: "US West",
    regionName: "us-west-1",
    availabilityZoneCount: 2,
  },
  {
    name: "Oregon",
    geography: "US West",
    regionName: "us-west-2",
    availabilityZoneCount: 4,
  },
];
